### ISSUE TITLE
When using "getUserSurveyList" method, at times the resulting survey list is empty

### ISSUE THREAD

**Issue by andramarin** [OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android#19]
Before, when we were using "getSurveyList" method, we didn't have any issues with the survey list.

Can you look into this?

**Comment by NeerajOPG** [comment]
Hi @andramarin 
There may be possibility that no surveys has been assigned to that panellist.
make sure that surveys are assigned to panellist.
Please check  [How to get surveys using panellist authentication?](https://github.com/OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android/wiki/03.-How-to-get-surveys-using-panellist-authentication%3F)

**Comment by andramarin** [comment]
There are surveys assigned to the panellist all the time. This happens only at times. 

We have followed the implementation from the link

**Comment by dinesh-opg** [comment]
Hi @andramarin  we are looking into the issue.we will get back to you on this.

**Comment by dinesh-opg** [comment]
Hi @andramarin  can you please test the project attached by passing your credentials .

[TestSdkLitev1.5.zip](https://github.com/OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android/files/1453946/TestSdkLitev1.5.zip)
As we are not able to replicate the issue.Can you mention scenarios where this issue is happening.

**Comment by andramarin** [comment]
I also tested this flow, it might help you:
- By using getUserSurveyList the surveys disappeared
- I changed back to getSurveyList, the surveys were back
- Got back to getUserSurveyList - surveys were gone
- Whatever I did no surveys were rendered
- Only after logging out and logging in I could see the list.

I suspect you do a logout in the background because this issues happens more or less once a day. What can you tell me about this? 

In order to test the app you sent me I should do this over two days and it takes too long.

**Comment by dinesh-opg** [comment]
Hi @andramarin 

 Which  version of opgsdk you are using ?

 Because the issue mentioned by you is present in the older sdk versions i.e 1.4 and below.
  We have fixed the session expiry issue in the opgsdklite version 1.5 .Can you please download the sdk from this [url](https://github.com/OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android/blob/master/OPGSDK_Lite/opgsdk_lite_v1.5.aar)  and test for the same.

**Comment by andramarin** [comment]
we are using version 1.5 lite

**Comment by dinesh-opg** [comment]
Are you getting any exceptions while calling getUserSurveyList .
Can you please download the sdk from this [url ](https://github.com/OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android/blob/master/OPGSDK_Lite/opgsdk_lite_v1.5.aar) and integrate ,test.

**Comment by dinesh-opg** [comment]
HI @andramarin we found the issue we will get back to you on this asap.

**Comment by dinesh-opg** [comment]
Hi @andramarin  we have fixed the issue related to the session expiry .Now you won't face this issue again.
