### ISSUE TITLE
Rejection of app due to this SDK as it needs cordova version update

### ISSUE THREAD

**Issue by Chinthan** [OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android#9]
The rejection of app as Cordova3.4.0 version used for SDK, it's considered to be vulnerable. So needs an update to the version SDK3.5.1.

**Comment by dinesh-opg** [comment]
The issue is releated to the cordova version present in the opgsdk lite .We will the update the cordova in the opgsdk lite

**Comment by dinesh-opg** [comment]
To fix the cordova issue please use the latest OPGSDK_Lite_V1.5 .You can download the sdk from the below link 

https://github.com/OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android/tree/master/OPGSDK_Lite_V1.5

**Comment by andramarin** [comment]
Is there a version of this release for iOS? We need both Android and iOS to be of the same version. 

In order to integrate the new version (OPGSDK_Lite_V1.5), we need a list of changes from v1.4 to v1.5. Can you provide us one? 
If this is a Lite version, we need to know the features are not included. 
By this  sentence,  "The folder OPGSDK_Lite_V1.5 contains the Lite version of the SDK to take online surveys only.", does it mean that we cannot access surveys offline? What about completion and finalising of a survey?

**Comment by Chinthan** [comment]
Please check the wiki 'Updates and Fixes' section for version release updates.
[iOS](https://github.com/OnePointGlobal/OnePoint-Global-Mobile-App-SDK-iOS/wiki/Updates-and-Fixes) [Android](https://github.com/OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android/wiki/Updates-and-Fixes)
If you use V1.5 then both will be in same code.

iOS having **OPGSDK_Lite_V1.5** and **OPGSDK_Full_V1.0**
Android only  **OPGSDK_Lite_V1.5**

**OPGSDK_Lite**  -  Its a lite version and it needs internet to run a survey. (No scripts will be downloaded to your mobile)

**OPGSDK_Full** - It has additional feature, where scripts can be downloaded to the device and that script can be used to run a survey without internet connection. (This feature is not released for android).

Next version of V1.4 is V1.5 with the updates and fixes mentioned above as 'OPGSDK_Lite_V1.5' and additional offline capabilities is added in 'OPGSDK_Full_V1.0'

As you are using V1.4 then you can upgrade the SDK to **OPGSDK_Lite_V1.5** in both the platforms.

What about completion and finalising of a survey? - You need internet connection till you finish the survey. Later you can see the survey results in admin toolkit (Export survey results).

Hope i answered your question. Let us know if you need more information.

**Comment by andramarin** [comment]
We have looked into the wiki documentation, but that info is not enough. 

Considering that the app should have been in store, already, we need to know if the methods from v1.4 are affected by the 1.5 version. This is why we are asking for a detailed documentation of the methods and parameters you are expecting and the results we receive by comparing version 1.4 with version 1.5.

Also can you tell me if v1.4 is a lite or a full SDK version?

**Comment by dinesh-opg** [comment]
Also can you tell me if v1.4 is a lite or a full SDK version?
v1.4 is lite version

In v1.4 tp v1.5 migration only one method name is changed from loadSurvey to loadOnlineSurvey(This is major change)

Implemented the refresh session internally in the SDK.

Made downloadMediaFile() method as non static from static method to make it compatible with other methods.

Added runtime permission request dialog inside survey.

And we have added more variables in the already existing model classes.
http://apidev.1pt.mobi/V3.0/Androiddoc/index.html

And also we have included geofencing monitoring methods.

**Considering that the app should have been in store, already, we need to know if there are breaking changes between the two versions so that we can release the app as soon as possible.**

There are many issues fixed and new features added .So it better to use the new SDK v1.5 instead of the old v1.4.
The below link provides you all the major changes and fixes

**Comment by andramarin** [comment]
Thanks for the info, the last response is really useful to usk. We will contact you if we have any issues.

**Comment by andramarin** [comment]
Hello, we have changed the SDK version to v1.5 and the app is still rejected by Google Play and removed all references to the v1.4. Can you help us on why they still detect Cordova less than 3.5.1 in our project?

**Comment by dinesh-opg** [comment]
Can you exactly share us from where you have downloaded the opgsdk v1.5. Please use this link to download the opgsdkv1.5
https://github.com/OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android/tree/master/OPGSDK_Lite_V1.5.

**Comment by andramarin** [comment]
I managed to release the app, it was a collision of the latest and current version in Google Play Console. Thank you for your response.

**Comment by dinesh-opg** [comment]
Hi Andramarin,

 Its good to hear that the app has been released .But i guess there is one more issue ,this app is not supported by any device .As there is a native library used in the app.Maybe you have used this library 
compile 'org.apache.directory.studio:org.apache.commons.io:2.4' in your build.gradle file.Please replace that with this compile 'commons-io:commons-io:2.4' line. Once these changes are done try to release app again.It should show all the supported devices as more than 0.
